In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB # GaussianNB doesn't work with sparse matrices
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

In [2]:
X = scipy.sparse.load_npz('data/train_tfidf.npz')
Y = np.loadtxt('data/train_labels.csv')

In [3]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.20)

In [4]:
Y_predict = Y_test.copy()
for i in range(Y.shape[1]):
    classifier = MultinomialNB()
    print('Training...')
    classifier.fit(X_train, Y_train[:,i])
    print('Predicting...')
    Y_predict[:,i] = classifier.predict(X_test)

Training...
Predicting...
Training...
Predicting...
Training...
Predicting...
Training...
Predicting...
Training...
Predicting...
Training...
Predicting...


In [5]:
import scipy
scipy.sparse.save_npz('output/MNB_X_train.npz', X_train)
np.savetxt('output/MNB_Y_train.out', Y_train)
scipy.sparse.save_npz('output/MNB_X_test.npz', X_test)
np.savetxt('output/MNB_Y_test.out', Y_test)
np.savetxt('output/MNB_Y_predict.out', Y_predict)

In [6]:
for i in range(Y.shape[1]):
    print("For feature %d" % (i+1))
    print("AUC = %f" % roc_auc_score(Y_test[:,i], Y_predict[:,i]))
    print(confusion_matrix(Y_test[:,i], Y_predict[:,i]))
    print(classification_report(Y_test[:,i], Y_predict[:,i]))

For feature 1
AUC = 0.531070
[[28842     1]
 [ 2881   191]]
              precision    recall  f1-score   support

         0.0       0.91      1.00      0.95     28843
         1.0       0.99      0.06      0.12      3072

   micro avg       0.91      0.91      0.91     31915
   macro avg       0.95      0.53      0.53     31915
weighted avg       0.92      0.91      0.87     31915

For feature 2
AUC = 0.500000
[[31618     0]
 [  297     0]]
              precision    recall  f1-score   support

         0.0       0.99      1.00      1.00     31618
         1.0       0.00      0.00      0.00       297

   micro avg       0.99      0.99      0.99     31915
   macro avg       0.50      0.50      0.50     31915
weighted avg       0.98      0.99      0.99     31915

For feature 3
AUC = 0.519438
[[30243     0]
 [ 1607    65]]
              precision    recall  f1-score   support

         0.0       0.95      1.00      0.97     30243
         1.0       1.00      0.04      0.07      1672

  

/usr/local/lib/python3.5/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.5/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00     31815
         1.0       0.00      0.00      0.00       100

   micro avg       1.00      1.00      1.00     31915
   macro avg       0.50      0.50      0.50     31915
weighted avg       0.99      1.00      1.00     31915

For feature 5
AUC = 0.503431
[[30312     0]
 [ 1592    11]]
              precision    recall  f1-score   support

         0.0       0.95      1.00      0.97     30312
         1.0       1.00      0.01      0.01      1603

   micro avg       0.95      0.95      0.95     31915
   macro avg       0.98      0.50      0.49     31915
weighted avg       0.95      0.95      0.93     31915

For feature 6
AUC = 0.500000
[[31647     0]
 [  268     0]]
              precision    recall  f1-score   support

         0.0       0.99      1.00      1.00     31647
         1.0       0.00      0.00      0.00       268

   micro avg       0.99      0.99      0.99     31915
   macro

/usr/local/lib/python3.5/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
