In [1]:
import numpy as np

In [2]:
# train labels
Y = np.loadtxt('data/train_labels.csv')
print(Y.shape)
print(Y[0,:])

(159571, 6)
[0. 0. 0. 0. 0. 0.]


In [3]:
# train tfidf
import scipy.sparse
tfidf = scipy.sparse.load_npz('data/train_tfidf.npz')
print(tfidf.shape)
print(tfidf[0,:])

(159571, 2305217)
  (0, 717002)	0.09585872373323574
  (0, 2214246)	0.05940868514487205
  (0, 636034)	0.049479200507628995
  (0, 2133382)	0.10030001412837637
  (0, 889930)	0.14481207066675264
  (0, 1264591)	0.1658159548931556
  (0, 739706)	0.10333860555257297
  (0, 1702608)	0.07017062550712938
  (0, 1316132)	0.08537293461626441
  (0, 2144741)	0.06947373061815727
  (0, 1071884)	0.051412056173061715
  (0, 393276)	0.1464737070050302
  (0, 813334)	0.10650578133532426
  (0, 2172972)	0.09742153819839953
  (0, 1342338)	0.06888352490206631
  (0, 2281323)	0.11097224466486742
  (0, 605513)	0.16257220087845636
  (0, 725487)	0.1270142646808814
  (0, 1506091)	0.05115933009309243
  (0, 1672228)	0.06184433187770314
  (0, 1987413)	0.08603295827818694
  (0, 1969094)	0.04685577385530582
  (0, 1434458)	0.045111262396673436
  (0, 1827140)	0.07008022423614965
  (0, 18058)	0.05950359167543954
  :	:
  (0, 2215063)	0.1429770918506515
  (0, 640805)	0.13967465929201722
  (0, 2133573)	0.2049489728127992
  (0, 889

In [4]:
# test labels
Y = np.loadtxt('data/test_labels.csv')
print(Y.shape)
print(Y[0,:])
print(Y[5000,:])

(153164, 6)
[1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0.]


In [5]:
# test tfidf
import scipy.sparse
tfidf = scipy.sparse.load_npz('data/test_tfidf.npz')
print(tfidf.shape)
print(tfidf[0,:])

(153164, 2361040)
  (0, 2225340)	0.07938794923236919
  (0, 243720)	0.12219966021027057
  (0, 1013872)	0.18414398835412954
  (0, 1688866)	0.11594098090816185
  (0, 1891179)	0.12001194410198628
  (0, 15743)	0.04846225054643715
  (0, 864622)	0.06169489813582889
  (0, 1698145)	0.0774345337008277
  (0, 1257734)	0.134804081309694
  (0, 1797273)	0.08911241769017564
  (0, 2071355)	0.07524871319199876
  (0, 1450314)	0.13942023928707942
  (0, 2165640)	0.12851703334613324
  (0, 694892)	0.0661730562853642
  (0, 1063572)	0.08370164568360848
  (0, 842718)	0.057499867225313334
  (0, 1775416)	0.10189764279991587
  (0, 1518869)	0.09207199417706477
  (0, 483927)	0.07343301205458322
  (0, 1279812)	0.06650710997357634
  (0, 1184136)	0.05775455308317231
  (0, 579781)	0.0632177774015934
  (0, 537010)	0.08378724643576833
  (0, 1766485)	0.054526361426855165
  (0, 1338510)	0.10716454053947976
  :	:
  (0, 2165914)	0.12515772531201694
  (0, 695276)	0.134804081309694
  (0, 1063652)	0.134804081309694
  (0, 843689)